In [12]:
import numpy as np
np_array=np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))

b=np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))



[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [19]:
x=np.zeros((4,5))
print(x)
y=np.full((3,3),7) # full with 7
print(y)
z=np.eye(6)
print(z) #identity matrix

ab=np.random.random((3,5)) #all between 0 and 1
print(ab)

aa=np.random.randint(10,100,(2,8))#random integers
print(aa)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[0.24191067 0.60500734 0.57453351 0.36477522 0.95081896]
 [0.82416127 0.9095189  0.99386279 0.32708172 0.91334476]
 [0.81825957 0.57572159 0.74778735 0.07958388 0.35382121]]
[[37 35 89 25 59 13 34 85]
 [89 46 50 76 71 27 34 15]]


In [22]:
#array of evenly spaced values
d=np.linspace(0,10,5)
print(d)

e=np.arange(0,10,3) #specify the steps
print(e)

[ 0.   2.5  5.   7.5 10. ]
[0 3 6 9]


In [25]:
#numpy list
list=[1,2,3,4,5,6,7]
np_array=np.asarray(list)
print(np_array)
type(np_array)

#analyze a numpy array
c=np.random.randint(10,90,(5,5))
print(c)
print(c.shape)
print(c.ndim)
print(c.size)
print(c.dtype)

[1 2 3 4 5 6 7]
[[84 14 71 26 29]
 [27 10 23 57 21]
 [28 59 14 22 13]
 [36 43 62 62 50]
 [40 50 41 86 13]]
(5, 5)
2
25
int64


In [26]:
#numpy operations

a=np.random.randint(5,25,(3,3))
b=np.random.randint(5,25,(3,3))
print(a)
print(b)
print(a+b)
print(np.add(a,b))

[[10 18  8]
 [17 22 12]
 [23 22  8]]
[[18 13 19]
 [20 15  8]
 [10 10 16]]
[[28 31 27]
 [37 37 20]
 [33 32 24]]
[[28 31 27]
 [37 37 20]
 [33 32 24]]
